# Generated by Django 4.2.9 on 2024-02-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gun', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
    ]
