# Generated by Django 4.2.9 on 2024-02-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gun', '0002_rename_user_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
