# Generated by Django 4.2.9 on 2024-02-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gun', '0003_alter_userdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
